### ISSUE TITLE
Getting semantic-release-cli to work

### ISSUE THREAD

**Issue by Flame2057** [kentcdodds/ama#178]
Hi, I've been watching your course on how to make an open source JavaScript library (and I've been loving it), but I'm stuck at the video where you install semantic-release-cli. Whenever I type what you typed to npm install it in git bash, I get this series of errors:

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
C:\Users\Owen\AppData\Roaming\npm\semantic-release-cli -> C:\Users\Owen\AppData\Roaming\npm\node_modules\semantic-release-cli\bin\semantic-release.js

> keytar@3.0.2 install C:\Users\Owen\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar
> node-gyp rebuild


C:\Users\Owen\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Users\Owen\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Owen\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\Owen\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Owen\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Owen\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\Owen\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Owen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "semantic-release-cli"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Owen\Desktop\GenerateID\npm-debug.log
npm ERR! code 1
```

Any idea what's going on here and how I can fix it? I tried uninstalling Node 4, then I installed Node 6, but the issue still persists.

Thanks.

**Comment by kentcdodds** [comment]
You need Python installed on your computer.

**Comment by kentcdodds** [comment]
If you have further issues, please file them on the [semantic-release](https://github.com/semantic-release/semantic-release) repo. Good luck! 😄
