### ISSUE TITLE
need help: syntax error thrown when running AVA test only

### ISSUE THREAD

**Issue by gnrlbzik** [kentcdodds/ama#209]
I can't figure out why node throws syntax error.

I am running node 7.0.0
I have koa 2 app, which runs on it's own fine

here is server code:
```
// initial server
const Koa = require('koa');
const app = module.exports = new Koa();
const send = require('koa-send');
const rtr = require('koa-router')();

const cnfgRoot = { root: __dirname };

// core routes
rtr.get('/', async (ctx, next) => {
    await send(ctx, 'views/index.html', cnfgRoot);
});

rtr.get('/signin', async (ctx, next) => {
    await send(ctx, 'views/signin.html', cnfgRoot);
});

rtr.get('/signup', async (ctx, next) => {
    await send(ctx, 'views/signup.html', cnfgRoot);
});

rtr.get('/adminka', async (ctx, next) => {
    await send(ctx, 'views/admin.html', cnfgRoot);
});

app.use(rtr.routes());
app.use(rtr.allowedMethods());

// serving static files from /public
app.use(async (ctx, next) => {
    await send(ctx, ctx.path, cnfgRoot);
});


if (!module.parent) {
    app.listen(3000);
    console.warn('listening on port 3000');
}

```

I am running AVA 0.16.0, it picks up this test and chokes on my app before it can get to any tests, test file looks like this:

```
const test = require('ava').test;
const app = require('./index');
const request = require('supertest').agent(app.listen());
```

when importing app.js into test to test end point, I get following error:

```
(node-v7.0.0) core.public (task/#3_#8_set-up-basic-routes-and-screens) x 🔩  ️yarn run server:test
yarn run v0.16.1
$ ava --watch server/**/*.test.js
/Users/gnrlbzik/core.public/server/index.js:10
rtr.get('/', async (ctx, next) => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Module._extensions..js (module.js:582:10)
    at extensions.(anonymous function) (/Users/gnrlbzik/core.public/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gnrlbzik/core.public/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gnrlbzik/core.public/server/index.test.js:2:13)
    at Module._compile (module.js:573:32)
    at extensions.(anonymous function) (/Users/gnrlbzik/core.public/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gnrlbzik/core.public/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gnrlbzik/core.public/node_modules/ava/lib/test-worker.js:96:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

```

**Comment by kentcdodds** [comment]
I believe that async/await are behind a flag on node 7. With that code, you probably don't really need async/await though... Could easily be the same thing with:

```js
rtr.get('/', (ctx, next) => send(ctx, 'views/index.html', cnfgRoot));
```

**Comment by gnrlbzik** [comment]
crap, i use nodemon and added 
```
  "execMap": {
    "js": "node --harmony"
  },
```
no wonder it works, when i run my server.

**Comment by gnrlbzik** [comment]
thank you @kentcdodds , lol
